version: '3.7'

networks:
  es_net:
    driver: bridge

volumes:
  esdata:

services:
  #
  ## ELASTICSEARCH
  #

  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: ta_elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks: 
      - es_net

  #
  ## KIBANA
  #
  # kibana:
  #   build:
  #     context: ./kibana
  #   container_name: ta_kibana
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - es_net

